---
abstract: 'Read redis aof file in realtime'
author:
  - 'Chen Gang <yikuyiku.com@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.133380'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Redis-AOF-Tail-File
no_index:
  directory:
    - t
    - inc
requires:
  File::Tail::Lite: 0.02
version: 0.06
